### ISSUE TITLE
Booked full logged time and log still open with 00:00 bookable time

### ISSUE THREAD

**Issue by cdokolas** [hicknhack-software/redmine_time_tracker#198] opened 2015-05-08 14:23 UTC
I had a time log of 1:05 which I booked by assigning the issue number and picking an activity, and now it is still visible with 00:00 bookable time.

Log details:
- Date: 06 May 2015
- Start time: 18:14
- End time: 19:19

**Comment by jume-dev** [comment] 2015-05-11 06:33
hi,
i am sorry, but please provide more informations, e.g. did you book some time from this timelog before?
In the end, try deleting the booking and create a new booking, sometimes this helps.

**Comment by cdokolas** [comment] 2015-05-11 11:14
I thought I made it clear on the issue title that I booked the full time all at once. I will try what you suggest, but I believe there is a bug none the less (i.e. I may use the workaround, but the issue should stay open).

Anything else you might need to reproduce the bug?

**Comment by jume-dev** [comment] 2015-05-11 11:40
well, anything helps ;)
The point is, we use this plugin in production everyday and it works as expected. So i need every information, you think is different from a default system.
Maybe other plugins, configuration, user acces roles and rights for this specific time log, etc.

**Comment by cdokolas** [comment] 2015-06-05 09:25
Oops! Hadn't seen your reply. Here you go with some more info:

From the Redmine information page:
```
Environment:
  Redmine version                2.6.5.stable
  Ruby version                   2.0.0-p353 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Mercurial                      2.8.2
  Git                            2.2.0
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  collapsed_journals             0.0.3
  redmine_better_gantt_chart     0.9.0
  redmine_favourite_projects     0.7
  redmine_slack                  0.1
  redmine_time_tracker           0.9.20
```
Also:
* There is another, in-house plugin, but it is only for time log reporting
* I'm set-up (user) to the GMT+2 timezone
* I was accessing Redmine with the English locale/language (selected via the browser's content language preferences) whenever the problem occurred

**Comment by hirmerpl** [comment] 2015-12-11 10:39
Hello,

I do have the same issue. After booking time to different tickets, a time log remains with 00:00h. A deletion of this time log is not possible.

Please find a screenshot of the problem attached. The version of the Timetracker Plugin I use is 0.10.5, the Redmine version is  3.1.2.stable.

![timetracker_issue](https://cloud.githubusercontent.com/assets/7569371/11741848/db6a983a-9ffb-11e5-855a-845a1dc3d040.png)

**Comment by jume-dev** [comment] 2015-12-11 15:55
Hi there,
the problem is that you have a missing minute from 04:28 to 04:29, but the time log doesn't display this right and says it's 0:00.
Change it, so that the start time of one is the stop time of the other. Then the timelog should be hidden.
Greetings,
jume

**Comment by hirmerpl** [comment] 2015-12-14 08:28
Thanks, that was the problem! :-)

Any idea why the time isn't displayed correctly? Maybe it is some kind of rounding issue.

**Comment by jume-dev** [comment] 2015-12-14 10:04
yeah, probably a rounding bug, will be fixed with the new release anytime soon

**Comment by jume-dev** [comment] 2015-12-14 10:05
whoops, forgot @cdokolas issue. But i guess that is kinda the same as the other one.

**Comment by jume-dev** [comment] 2017-05-22 10:20
These kind of problems are fixed with the [new version](https://github.com/hicknhack-software/redmine_hourglass).

**Closed by jume-dev** 2017-05-22 10:20 UTC
